# Generated by Django 5.2.5 on 2026-01-03 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile'), ('card', 'Card')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
