# Generated by Django 5.2.5 on 2026-01-06 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.DateField(help_text='Use first day of the month (e.g. 2026-01-01).')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='expenses.rawmaterial')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.unit')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='default_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='expenses.unit'),
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('utility_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='expenses.utilitytype')),
            ],
        ),
    ]
