# Generated by Django 5.2.5 on 2026-01-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
