# Generated by Django 6.0.1 on 2026-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_discount_amount_orderitem_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
