# Generated by Django 6.0.1 on 2026-02-22 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit = grand_total - total_cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of goods sold (COGS) for this order', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price per unit at time of sale (auto-filled from product)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost for this line (cost_price * qty)', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit for this line (line_total - line_cost)', max_digits=10),
        ),
    ]
